# services:
#   _defaults:
#     autowire: true
#     autoconfigure: true
#     public: false
 
#   Web7\Market\:
#     resource: '../Classes/*'
    

  # Web7\Market\Command\DoSomethingCommand:
  #   tags:
  #     - name: console.command
  #       command: 'examples:dosomething'
  #       description: 'A command that does nothing and always succeeds.'